version: "3.2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm
    image: mermaid-landing-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    #environment:
    #  - name=value
    networks:
      - internal-communication

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports:
      - "8081:80"
      #- "443:443"
    networks:
      - internal-communication

networks:
  internal-communication:
    driver: bridge
    external: false
