branch-defaults:
  main:
    environment: $EB_ENV_NAME$
    development:
      environment: $EB_ENV_DEV_NAME$
global:
  application_name: $EB_APP_NAME$
  default_ec2_keyname: $EB_KEY_NAME$
  default_platform: PHP 8.0 running on 64bit Amazon Linux 2/3.3.5
  default_region: $EB_REGION$
  sc: git
deploy:
  artifact: main.zip
