version: '2.1'
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@5.0.2
jobs:
  deploy-beanstalk:
    parameters:
      app-dir:
          default: .
          description: Path to the directory containing your application source code. My default, the current directory will be used.
          type: string
      application-name:
          default: ""
          description: The name of the application (used during `eb init`).
          type: string
      description:
          default: ""
          description: The description for the application version, enclosed in double quotation marks.
          type: string
      environment-name:
          default: ""
          description: The name of the existing environment (created with `eb create`) to update.
          type: string
      image:
          default: cimg/base:stable
          description: Enter a custom docker image for this job. By default CircleCI's optimized `cimg/base` image will be used.
          type: string
      label:
          default: ""
          description: Specify a label to use for the version that the EB CLI creates. If the label has already been used, the EB CLI redeploys the previous version with that label.
          type: string
      platform-version:
          default: node.js
          description: The platform version to use. You can specify a platform, a platform and version, a platform branch, a solution stack name, or a solution stack ARN. Use 'eb platform list' to get a list of available configurations.
          type: string
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - eb/setup
      - run:
          command: |
              eb init <<parameters.application-name>> -r $AWS_DEFAULT_REGION -p <<parameters.platform-version>>
              eb deploy <<parameters.environment-name>> <<#parameters.label>>-l <<parameters.label>><</parameters.label>> <<#parameters.description>>-m <<parameters.description>><</parameters.description>>
          name: EB Deploy
          working_directory: <<parameters.app-dir>>

  install-node:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version

workflows:
  elastic-beanstalk-workflow:
    jobs:
      - install-node
      - node/run:
          post-steps:
            - persist_to_workspace:
                root: .
                paths:
                  - public/js
                  - public/css
                  - public/fonts
                  - public/mix-manifest.json
          npm-run: production
          filters:
            branches:
              only:
                - staging
                - main
      - deploy-beanstalk:
          context: aws-mermaid-landing
          application-name: $EB_APP_NAME
          environment-name: $EB_ENV_NAME_STAGING
          platform-version: $EB_PLATFORM
          filters:
            branches:
              only:
                - staging
          label: version-stag-${CIRCLE_SHA1}
          requires:
            - node/run
      - deploy-beanstalk:
          context: aws-mermaid-landing
          application-name: $EB_APP_NAME
          environment-name: $EB_ENV_NAME_PRODUCTION
          platform-version: $EB_PLATFORM
          filters:
            branches:
              only:
                - main
          label: version-prod-${CIRCLE_SHA1}
          requires:
            - node/run
