sections:
  main:
    display: Main
    fields:
      -
        handle: site_name
        field:
          input_type: text
          antlers: false
          display: 'Site Name'
          type: text
          icon: text
          listable: hidden
      -
        handle: fav_icon
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          display: 'Fav Icon'
          type: assets
          icon: assets
          listable: hidden
          max_files: 1
      -
        handle: logo
        field:
          mode: grid
          restrict: false
          allow_uploads: true
          display: Logo
          type: assets
          icon: assets
          listable: hidden
          max_files: 1
  cookies_alert:
    display: 'Cookies Alert'
    fields:
      -
        handle: cookies_alert_title
        field:
          input_type: text
          antlers: false
          display: Title
          type: text
          icon: text
          listable: hidden
          default: 'We use cookies to give you the best online experience.'
      -
        handle: cookies_alert_lead
        field:
          init: |-
            {
            	"height": 500,
            	"menubar": false,
            	"plugins": [
            		"advlist autolink lists link image charmap print preview anchor footnotes",
            		"searchreplace visualblocks code fullscreen",
            		"insertdatetime media table paste code help wordcount",
            		"code"
            	],
            	"external_plugins": {
            		"footnotes": "/public/vendor/tinymce/footnotes/plugin.js"
            	},
            	"toolbar": "undo redo | formatselect | bold italic backcolor | blockquote | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | footnotes | removeformat | code"
            }
          display: Lead
          type: tinymce_cloud
          icon: textarea
          listable: hidden
